n = input('digite algo:')
print ('o tipo primitivo desse valor:', type(n))
print ('n so tem esapço?',n.isspace())
print ('n é um numero?:',n.isnumeric())
print('é alfabetico?:',n.isalpha())
print('é alfanumerico?:',n.isalnum())
print('é maiuscula?:',n.isupper())
print('é minuscula?:',n.islower())
print('esta capitalziado:',n.istitle())